name: Desplegar a Hostinger

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Compilar y Subir
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Obtener el código de GitHub
        uses: actions/checkout@v4

      - name: ⚙️ Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: 📦 Instalar dependencias
        run: npm install

      - name: 🛠️ Compilar el proyecto (Vite)
        run: npm run build

      - name: 🚀 Subir archivos a Hostinger (FTP)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist/
          server-dir: /public_html/
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            blog/**
            .htaccess
